all:
    children:
        manager:
            hosts:
                swarm-manager:
                    ansible_connection: ssh
                    ansible_user: root
                    ansible_host: 195.161.68.104
                    ansible_port: 49347

        workers:
            hosts:
                swarm-worker-1:
                    ansible_connection: ssh
                    ansible_user: root
                    ansible_host: ovz6.j49321827.px7zm.vps.myjino.ru
                    ansible_port: 49291