all:
    children:
        site:
            hosts:
                server:
                    ansible_connection: ssh
                    ansible_user: root
                    ansible_host: 195.161.68.104
                    ansible_port: 49347