---
-   name: Provision manager
    hosts: manager
    remote_user: root
    roles:
      - docker
      - certbot
      - swarm-manager

-   name: Provision worker
    hosts: workers
    remote_user: root
    roles:
      - docker
      - swarm-worker